// Mirrors financial_statements/standard_items.py STANDARD_LABELS, plus the
// display order each statement type's rows should render in (top to bottom,
// the way a real financial statement reads).

export const INCOME_STATEMENT_ORDER = [
  "revenue",
  "cost_of_revenue",
  "gross_profit",
  "sga_expenses",
  "other_operating_expense",
  "operating_expenses",
  "operating_income",
  "interest_expense",
  "other_income_expense",
  "pretax_income",
  "income_tax_expense",
  "net_income",
  "eps_basic",
  "eps_diluted",
] as const;

export const BALANCE_SHEET_ORDER = [
  "cash_and_equivalents",
  "short_term_investments",
  "accounts_receivable",
  "inventory",
  "other_current_assets",
  "total_current_assets",
  "ppe_net",
  "goodwill_and_intangibles",
  "long_term_investments",
  "other_noncurrent_assets",
  "total_noncurrent_assets",
  "total_assets",
  "accounts_payable",
  "short_term_debt",
  "other_current_liabilities",
  "total_current_liabilities",
  "long_term_debt",
  "other_noncurrent_liabilities",
  "total_noncurrent_liabilities",
  "total_liabilities",
  "common_stock",
  "retained_earnings",
  "other_equity",
  "total_equity",
  "total_liabilities_and_equity",
] as const;

export const CASH_FLOW_ORDER = [
  "other_operating_activities",
  "cash_from_operations",
  "capital_expenditures",
  "other_investing_activities",
  "cash_from_investing",
  "common_stock_issued",
  "debt_issued",
  "debt_repaid",
  "dividends_paid",
  "fx_effect",
  "other_financing_activities",
  "cash_from_financing",
  "net_change_in_cash",
  "cash_beginning_balance",
  "cash_ending_balance",
] as const;

export const STATEMENT_ROW_ORDER = {
  income_statement: INCOME_STATEMENT_ORDER,
  balance_sheet: BALANCE_SHEET_ORDER,
  cash_flow: CASH_FLOW_ORDER,
} as const;

// Rows that should render in bold / with a top border, the way a real
// statement sets off subtotals from detail lines.
export const SUBTOTAL_KEYS = new Set([
  "gross_profit",
  "operating_income",
  "pretax_income",
  "net_income",
  "total_current_assets",
  "total_noncurrent_assets",
  "total_assets",
  "total_current_liabilities",
  "total_noncurrent_liabilities",
  "total_liabilities",
  "total_equity",
  "total_liabilities_and_equity",
  "cash_from_operations",
  "cash_from_investing",
  "cash_from_financing",
  "net_change_in_cash",
]);

export const STANDARD_LABELS: Record<string, string> = {
  revenue: "Revenue",
  cost_of_revenue: "Cost of Revenue",
  gross_profit: "Gross Profit",
  sga_expenses: "SG&A Expenses",
  other_operating_expense: "Other Operating Expenses",
  operating_expenses: "Operating Expenses",
  operating_income: "Operating Income",
  interest_expense: "Interest Expense",
  other_income_expense: "Other Income (Expense)",
  pretax_income: "Pretax Income",
  income_tax_expense: "Income Tax Expense",
  net_income: "Net Income",
  eps_basic: "EPS (Basic)",
  eps_diluted: "EPS (Diluted)",
  cash_and_equivalents: "Cash & Equivalents",
  short_term_investments: "Short-Term Investments",
  accounts_receivable: "Accounts Receivable",
  inventory: "Inventory",
  other_current_assets: "Other Current Assets",
  total_current_assets: "Total Current Assets",
  ppe_net: "Property, Plant & Equipment",
  goodwill_and_intangibles: "Goodwill & Intangible Assets",
  long_term_investments: "Long-Term Investments",
  other_noncurrent_assets: "Other Non-Current Assets",
  total_noncurrent_assets: "Total Non-Current Assets",
  total_assets: "Total Assets",
  accounts_payable: "Accounts Payable",
  short_term_debt: "Short-Term Debt",
  other_current_liabilities: "Other Current Liabilities",
  total_current_liabilities: "Total Current Liabilities",
  long_term_debt: "Long-Term Debt",
  other_noncurrent_liabilities: "Other Non-Current Liabilities",
  total_noncurrent_liabilities: "Total Non-Current Liabilities",
  total_liabilities: "Total Liabilities",
  common_stock: "Common Stock",
  retained_earnings: "Retained Earnings",
  other_equity: "Other Equity",
  total_equity: "Total Equity",
  total_liabilities_and_equity: "Total Liabilities & Equity",
  other_operating_activities: "Other Operating Activities",
  cash_from_operations: "Cash from Operations",
  capital_expenditures: "Capital Expenditures",
  other_investing_activities: "Other Investing Activities",
  cash_from_investing: "Cash from Investing",
  common_stock_issued: "Common Stock Issued",
  debt_issued: "Debt Issued",
  debt_repaid: "Debt Repaid",
  dividends_paid: "Dividends Paid",
  fx_effect: "Effect of Exchange Rate Changes",
  other_financing_activities: "Other Financing Activities",
  cash_from_financing: "Cash from Financing",
  net_change_in_cash: "Net Change in Cash",
  cash_beginning_balance: "Cash - Beginning of Period",
  cash_ending_balance: "Cash - End of Period",
};

export const STATEMENT_TYPE_LABELS: Record<string, string> = {
  income_statement: "صورت سود و زیان",
  balance_sheet: "ترازنامه",
  cash_flow: "صورت جریان وجوه نقد",
};

export const STANDARD_LABELS_FA: Record<string, string> = {
  revenue: "درآمد عملیاتی",
  cost_of_revenue: "بهای تمام‌شده",
  gross_profit: "سود ناخالص",
  sga_expenses: "هزینه‌های فروش، اداری و عمومی",
  other_operating_expense: "سایر هزینه‌های عملیاتی",
  operating_expenses: "جمع هزینه‌های عملیاتی",
  operating_income: "سود عملیاتی",
  interest_expense: "هزینه‌های مالی",
  other_income_expense: "سایر درآمدها و هزینه‌ها",
  pretax_income: "سود قبل از مالیات",
  income_tax_expense: "مالیات بر درآمد",
  net_income: "سود خالص",
  eps_basic: "سود هر سهم (پایه)",
  eps_diluted: "سود هر سهم (تقلیل‌یافته)",
  cash_and_equivalents: "موجودی نقد",
  short_term_investments: "سرمایه‌گذاری‌های کوتاه‌مدت",
  accounts_receivable: "دریافتنی‌های تجاری",
  inventory: "موجودی مواد و کالا",
  other_current_assets: "سایر دارایی‌های جاری",
  total_current_assets: "جمع دارایی‌های جاری",
  ppe_net: "دارایی‌های ثابت مشهود",
  goodwill_and_intangibles: "دارایی‌های نامشهود",
  long_term_investments: "سرمایه‌گذاری‌های بلندمدت",
  other_noncurrent_assets: "سایر دارایی‌های غیرجاری",
  total_noncurrent_assets: "جمع دارایی‌های غیرجاری",
  total_assets: "جمع دارایی‌ها",
  accounts_payable: "پرداختنی‌های تجاری",
  short_term_debt: "تسهیلات مالی کوتاه‌مدت",
  other_current_liabilities: "سایر بدهی‌های جاری",
  total_current_liabilities: "جمع بدهی‌های جاری",
  long_term_debt: "تسهیلات مالی بلندمدت",
  other_noncurrent_liabilities: "سایر بدهی‌های غیرجاری",
  total_noncurrent_liabilities: "جمع بدهی‌های غیرجاری",
  total_liabilities: "جمع بدهی‌ها",
  common_stock: "سرمایه",
  retained_earnings: "سود انباشته",
  other_equity: "سایر اقلام حقوق صاحبان سهام",
  total_equity: "جمع حقوق صاحبان سهام",
  total_liabilities_and_equity: "جمع بدهی‌ها و حقوق صاحبان سهام",
  other_operating_activities: "سایر فعالیت‌های عملیاتی",
  cash_from_operations: "جریان نقد عملیاتی",
  capital_expenditures: "مخارج سرمایه‌ای",
  other_investing_activities: "سایر فعالیت‌های سرمایه‌گذاری",
  cash_from_investing: "جریان نقد سرمایه‌گذاری",
  common_stock_issued: "افزایش سرمایه",
  debt_issued: "دریافت تسهیلات",
  debt_repaid: "بازپرداخت تسهیلات",
  dividends_paid: "سود سهام پرداختی",
  fx_effect: "تأثیر نرخ ارز",
  other_financing_activities: "سایر فعالیت‌های تأمین مالی",
  cash_from_financing: "جریان نقد تأمین مالی",
  net_change_in_cash: "خالص تغییر در موجودی نقد",
  cash_beginning_balance: "موجودی نقد ابتدای دوره",
  cash_ending_balance: "موجودی نقد پایان دوره",
};
