/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Y8onI5jOv7U
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { CardContent, Card } from "@/components/ui/card"
import { ResponsiveLine } from "@nivo/line"

export function Component() {
  return (
    <div className="min-h-screen bg-white">
      <header className="bg-[#003366] p-4">
        <div className="container mx-auto flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <MenuIcon className="text-white" />
            <div className="text-white text-2xl font-bold">Stock Unlock</div>
          </div>
          <div className="flex items-center space-x-4">
            <Input placeholder="Search 170,000+ Stocks & ETFs" type="search" />
            <Button className="bg-[#00aeef] text-white">Invite Friends</Button>
            <MoonIcon className="text-white" />
            <Button className="bg-[#ffcc00] text-[#003366]">UPGRADE</Button>
          </div>
        </div>
      </header>
      <div className="container mx-auto mt-4 p-4">
        <div className="grid grid-cols-4 gap-4">
          <aside className="col-span-1">
            <nav className="bg-[#e6e6e6] p-4 rounded-lg">
              <ul className="space-y-2">
                <li>
                  <Button className="w-full justify-start rounded-lg bg-[#003366] text-white">Home</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">Portfolios</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">Find New Stocks</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">Track Stocks</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">Compare Stocks</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">DCF Calculator</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">Newsletters</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">Glossary</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg">Discord</Button>
                </li>
                <li>
                  <Button className="w-full justify-start rounded-lg bg-[#00aeef] text-white">Tutorial & Tips</Button>
                </li>
              </ul>
            </nav>
          </aside>
          <main className="col-span-3">
            <div className="bg-[#00aeef] text-white p-4 rounded-lg">
              <h2 className="text-xl font-bold">Video guide: Unlock the power of your portfolio</h2>
              <Button className="mt-2">Watch Tutorial</Button>
              <div className="mt-2 flex items-center">
                <Checkbox id="hide-tutorials" />
                <label className="ml-2" htmlFor="hide-tutorials">
                  Check to hide ALL tutorials
                </label>
              </div>
            </div>
            <div className="mt-4 grid grid-cols-3 gap-4">
              <Card className="w-full">
                <CardContent>
                  <LinkIcon className="text-[#00aeef]" />
                  <h3 className="text-lg font-semibold mt-2">Connect Brokerage</h3>
                  <p className="mt-1">Link your brokerages in minutes.</p>
                </CardContent>
              </Card>
              <Card className="w-full">
                <CardContent>
                  <FileIcon className="text-[#00aeef]" />
                  <h3 className="text-lg font-semibold mt-2">CSV or Manual Entry</h3>
                  <p className="mt-1">Upload a CSV or manually enter your portfolio.</p>
                </CardContent>
              </Card>
              <Card className="w-full">
                <CardContent>
                  <EyeIcon className="text-[#00aeef]" />
                  <h3 className="text-lg font-semibold mt-2">Try Demo Portfolio</h3>
                  <p className="mt-1">Just one click to create a demo portfolio!</p>
                </CardContent>
              </Card>
            </div>
            <section className="mt-4">
              <h2 className="text-xl font-bold">Indexes</h2>
              <div className="mt-2 grid grid-cols-2 gap-4">
                <div className="bg-[#e6e6e6] p-4 rounded-lg">
                  <h3 className="text-lg font-semibold">Dow Jones CFD</h3>
                  <p>37,500.70 +0.01%</p>
                </div>
                <div className="bg-[#e6e6e6] p-4 rounded-lg">
                  <h3 className="text-lg font-semibold">S&P/TSX CFD</h3>
                  <p>20,937.55 +0%</p>
                </div>
                <div className="bg-[#e6e6e6] p-4 rounded-lg">
                  <h3 className="text-lg font-semibold">S&P 500 CFD</h3>
                  <p>4,701.60 -0.03%</p>
                </div>
                <div className="bg-[#e6e6e6] p-4 rounded-lg">
                  <h3 className="text-lg font-semibold">Nasdaq 100 CFD</h3>
                  <p>16,318.80 -0.04%</p>
                </div>
              </div>
            </section>
            <section className="mt-4">
              <CurvedlineChart className="w-full aspect-[16/9]" />
            </section>
          </main>
        </div>
      </div>
    </div>
  )
}


function MenuIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MoonIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
  )
}


function LinkIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}


function FileIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}


function EyeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function CurvedlineChart(props:any) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "B",
            data: [
              { x: "2018-01-01", y: 7 },
              { x: "2018-01-02", y: 5 },
              { x: "2018-01-03", y: 11 },
              { x: "2018-01-04", y: 9 },
              { x: "2018-01-05", y: 12 },
              { x: "2018-01-06", y: 16 },
              { x: "2018-01-07", y: 13 },
              { x: "2018-01-08", y: 13 },
            ],
          },
          {
            id: "A",
            data: [
              { x: "2018-01-01", y: 9 },
              { x: "2018-01-02", y: 8 },
              { x: "2018-01-03", y: 13 },
              { x: "2018-01-04", y: 6 },
              { x: "2018-01-05", y: 8 },
              { x: "2018-01-06", y: 14 },
              { x: "2018-01-07", y: 11 },
              { x: "2018-01-08", y: 12 },
            ],
          },
        ]}
        enableCrosshair={false}
        margin={{ top: 50, right: 110, bottom: 50, left: 60 }}
        xScale={{
          type: "time",
          format: "%Y-%m-%d",
          useUTC: false,
          precision: "day",
        }}
        xFormat="time:%Y-%m-%d"
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "X",
          legendOffset: 45,
          legendPosition: "middle",
          format: "%b %d",
          tickValues: "every 1 day",
        }}
        axisLeft={{
          tickSize: 5,
          tickPadding: 5,
          tickRotation: 0,
          legend: "Y",
          legendOffset: -45,
          legendPosition: "middle",
        }}
        colors={{ scheme: "paired" }}
        pointSize={5}
        pointColor={{
          from: "color",
          modifiers: [["darker", 0.2]],
        }}
        pointBorderWidth={2}
        pointBorderColor={{
          from: "color",
          modifiers: [["darker", 0.2]],
        }}
        pointLabelYOffset={-12}
        useMesh={true}
        curve="monotoneX"
        legends={[
          {
            anchor: "bottom-right",
            direction: "column",
            justify: false,
            translateX: 100,
            translateY: 0,
            itemsSpacing: 0,
            itemDirection: "left-to-right",
            itemWidth: 80,
            itemHeight: 20,
            symbolSize: 14,
            symbolShape: "circle",
          },
        ]}
        theme={{
          tooltip: {
            container: {
              fontSize: "12px",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
